language: php
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

env:
  - DB=mysql

services:
  - memcached # will start memcached
  - mongodb


# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test1;" -uroot; fi
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp -rf conf/Main.travis.php conf/Main.php
  - nohup node travis/http-mirror.js &
  - nohup php -S localhost:8000 travis/http-server.php &

script:
  - phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
